<?php
/**
 * AIMS
 * @category   AIMS
 * @package    Aims_Hypnia
 * @copyright  Copyright (c) 2020 Unicode Systems. (http://www.unicodesystems.in)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php $_availablePledgMethods = $this->getAvailableMethods(); ?>

<?php if(count($_availablePledgMethods) > 0) : ?>
    <?php foreach($_availablePledgMethods as $_method) : ?>
        <div class="pledg_payment_methods">
            <input type="radio" name="payment[pledg_method]" id="<?php echo $_method->getCode(); ?>" value="<?php echo $_method->getCode(); ?>" class="validate-one-required-by-name"/>
            <label for="<?php echo $_method->getCode(); ?>">
                <span class="title"><?php echo $_method->getTitle(); ?></span>
                <span class="description"><?php echo $_method->getDescription(); ?></span>
            </label>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
