<?php
/**
 * AIMS
 * @category   AIMS
 * @package    Aims_Hypnia
 * @copyright  Copyright (c) 2020 Unicode Systems. (http://www.unicodesystems.in)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php $description = $this->getMethod()->getConfigData('description'); ?>
<?php if ($description) : ?>
    <span class="description"><?php echo $description; ?></span>
<?php endif; ?>
